# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

after_success:
    - Rscript -e 'covr::codecov()'

before_install:
  # Manually compile the libsodium library
  - sudo apt-get install -y libsodium-dev
