#' Title
#'
#' @param data
#' @param drop_rare_values_cols
#' @param preferred_k_score
#' @param file_name
#' A string with the name of the PDF file that will be generated by the function. Must end in '.pdf'. The file will be generated in the current working directory.
#'
#' @return
#' @export
#'
#' @examples
make_deidentify_choices_reported <- function(data,
                                             drop_rare_values_cols,
                                             preferred_k_score = NULL,
                                             file_name) {

  date_cols <- sapply(data, class)
  date_cols <- date_cols[date_cols == "Date"]
  if (length(date_cols) > 0) {
    date_cols <- names(date_cols)
    date_aggregate_list <- list()
    for (col in date_cols) {
      date_aggregate_list <- list(date_aggregate_list,
                                  graph_aggregate_dates(data[, col]))
    }
    names(date_aggregate_list) <- paste0("Date column: ", date_cols)
  }


  rare_value_list <- list()
  for (col in drop_rare_values_cols) {
    rare_value_list <- list(rare_value_list,
                            graph_group_rare_values(data[, col]))
  }
  names(rare_value_list) <- paste0("Drop rare values column: ", drop_rare_values_cols)


  choices_table_all <- deidentify_choices_table(data,
                                                drop_rare_values_cols)
  if (!is.null(preferred_k_score)) {
    choices_table_preferred <- deidentify_choices_table(data,
                                                        drop_rare_values_cols,
                                                        preferred_k_score)
  } else {
    choices_table_preferred <- NULL
  }

  rmarkdown::render("deidentify_choices_reported.Rmd",
                    params = list(
                      data = example,
                      set_title = "An evaluation of the effect of de-identification choices on your data",
                      graphs_list = date_aggregate_list,
                      rare_value_list = rare_value_list,
                      choices_table_preferred = choices_table_preferred,
                      choices_table_all = choices_table_all
                    ),
                    output_file = file_name)
}
